### ISSUE TITLE
error python -m pricePrediction.predict -h

### ISSUE THREAD

**Issue by Nick-Mul** [rsanchezgarc/CoPriNet#2]
Looks a useful package and it was a good poster,  I am sorry to say I was having a issue running this.... maybe me.

install via conda (despite my dislike for it) from the yaml file 

`conda env create -f CoPriNet_env.yml`

but running 

`python -m pricePrediction.predict -h`

I get the following error:
from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

This is before I even battle with cuda versions :) 

If relevant I am running NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7 on an A100,
with RHEL 8

**Comment by rsanchezgarc** [comment]
Hi,

Thank you very much for your feedback. I have updated the .yml file, so now it should work again. Pytorch-related packages can be painful many times.

Let me know if you face more problems installing it.

**Comment by Nick-Mul** [comment]
Great thanks Ruben, that fixed it!
