### ISSUE TITLE
Output interpretation

### ISSUE THREAD

**Issue by JoeDavies-6** [rsanchezgarc/CoPriNet#5]
What are the units of the output? I.e., is it £ per mol/g/mg/mmol?

Sorry if this is documented somewhere but I couldn't find it.
This was the output I received for these SMILES.

OC(=O)c1cnccn1,	2.4396858215332,
Cc1ccc(C(=O)Nc2ccc(N3CCN(CC3)C(=O)c3ccco3)c(Cl)c2)c(C)c1,	3.17332887649536,
CCOC(=O)N1CCc2cc(ccc12)[N+]([O-])=O,	2.80040693283081

Thanks!

**Comment by rsanchezgarc** [comment]
It is in $/mmol. You have a flag in the command line (--convert_to_g) to get it in grams.
No worries

**Comment by JoeDavies-6** [comment]
Thanks very much!
